name: Evaluate Candidate Submission with Ollama

on:
  workflow_dispatch:
  push:
    branches: [main, master]

jobs:
  evaluate-candidate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Ollama
        run: |
          curl -fsSL https://ollama.com/install.sh | sh
          echo "Starting Ollama server in background..."
          nohup ollama serve > /dev/null 2>&1 &
          sleep 10

      - name: Pull LLM model
        run: ollama pull codellama

      - name: Prepare and Analyze Code
        run: |
          echo "Reading test description..."
          TEST_DESCRIPTION=$(cat test_description.txt)

          echo "Collecting candidate code..."
          CODE=""
          for file in $(find src -type f ! -iname "*.png" ! -iname "*.jpg" ! -iname "*.ico" ! -iname "*.svg"); do
            CODE+="\n\n--- FILE: $file ---\n"
            CODE+="$(cat "$file")"
          done

          echo "Building prompt..."
          PROMPT="You are a senior developer evaluating a technical test submission.\n

                  Here is the test the candidate was asked to complete:

                  $TEST_DESCRIPTION

                  Here is the candidate's submitted code:

                  $CODE\n

                  Please carefully review the code and provide your evaluation using the following structure.\n

                  ### Expected Response Format:

                  **1. Completion Estimate (%):**
                  Provide an approximate percentage of how much of the test is complete.

                  **2. Successfully Completed Tasks:**
                  - Task 1
                  - Task 2
                  ...

                  **3. Summary of the Candidate's Implementation:**
                  Write a concise paragraph summarizing the codebase structure, key design decisions, and how the logic works.

                  **4. Areas of Improvement or Missing Parts:**
                  - Missing Feature: ...
                  - Code Quality: ...
                  - Performance: ...
                  - Security: ...
                  - Best Practices: ...
                  "

          echo -e "$PROMPT" | ollama run codellama
